POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "bob",
    "email": "bob@gmail.com",
    "password": "bob@1234"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "bob@gmail.com",
    "password": "bob@1234"
}
